---
    local_loopback:
      - name: Loopback1
        desc: Sample Ansible config
        ip_address: 1.1.1.1/32
      - name: Loopback2
        desc: Sample Ansible config
        ip_address: 11.11.11.11/32

    
    interfaces:
      - name: GigabitEthernet1
        ip_address: 10.10.21.15/24
      - name: GigabitEthernet2
        ip_address: 172.16.16.1/30
      - name: GigabitEthernet3
        ip_address: 10.99.99.9/30